### ISSUE TITLE
Publish documentation to gh-pages?

### ISSUE THREAD

**Issue by tobiasake** [eiffel-community/eiffel-event-repository#5]
### Description
How should we publish documentation to gh-pages?
Today in Eiffel-Intelligence we convert markdown documentation to html files with the 'mvn site' command.
The issue with that is relative paths in markdown format do not work in html format after format conversions. One work around is to use full paths links to the master branch version of the markdown file. This is not good from a PR:s view , where it should point out PR version of the documentation and not the master branch verison of the specific documentation link/markdown file.

Investigate if this can improved for the Eiffel-ER gh-pages documentation.

**Comment by e-pettersson-ericsson** [comment]
Since we have moved in the opposite direction for other repositories, choosing to keep the documentation within the repository to ease maintainability I suppose this issue is no longer valid. If somebody wants to have documentation published on github pages they can open a new issue in the future.
